use_frameworks!

platform :ios, '10.0'

target 'LXMasonry_Example' do
  pod 'LXMasonry', :path => '../'

  target 'LXMasonry_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
